---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unimorph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unimorph
  template:
    metadata:
      labels:
        app: unimorph
    spec:
      nodeSelector:
        app: unimorph
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        - name: frontend
          image: thehubaubg/unimorph-frontend
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-conf
            readOnly: true
        
        - name: backend
          image: thehubaubg/unimorph-backend
          command: [ "/bin/bash" ]
          args: [ "./wait-for-it.sh", "$(DB_HOST):5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000" ]
          ports:
          - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: eureka.settings.production
            
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-host
                  key: secretKey
            
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: secretKey
            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: secretKey
            
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-name
                  key: secretKey

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: secretKey
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"